spring.application.name=mobilestore
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
pring.jpa.properties.hibernate.format-sql=true
spring.jackson.property-naming-strategy=LOWER_CASE
